### ISSUE TITLE
Stages of the Activity Lifecycle: Android Basics in Compose

### ISSUE THREAD

**Issue by Jonathan5579** [google-developer-training/basic-android-kotlin-compose-training-dessert-clicker#14]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-activity-lifecycle#2

**In which task and step of the codelab can this issue be found?**
7. In the Logcat window, type MainActivity into the search field.

**Describe the problem**
Created both logs, none of them appear in the Logcat tab, just shows two lines:
---------------------------- PROCESS STARTED (25295) for package com.example.dessertclicker ----------------------------
2023-03-06 12:18:54.906  1156-1451  ArtManagerInternalImpl  system_server                        D  /data/misc/iorapd/com.example.dessertclicker/1/com.example.dessertclicker.MainActivity/compiled_traces/compiled_trace.pb doesn't exist, 
it
It's the same with the solution coed and without having any logs.

**Steps to reproduce?**
1. Go to... Logcat tab
2. Click on... search tab and write D/MainActivity
3. See error... 2023-03-06 12:18:54.906  1156-1451  ArtManagerInternalImpl  system_server                        D  /data/misc/iorapd/com.example.dessertclicker/1/com.example.dessertclicker.MainActivity/compiled_traces/compiled_trace.pb doesn't exist

**Versions**
_Android Studio version:_ Electric Eel 2022.1.1 patch 1
_API version of the emulator:_  not an emulator, a tablet labeled Samsung SM-T540 with android version

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Jonathan5579 

Thank you for writing in about your issue.
 
Please attach a screenshot so we can see what you have in the Logcat pane.

It would also be helpful if you include a link to your full project (preferable) or at least attach your MainActivity.kt file to confirm it is coded correclty.

You could also try setting up an emulator and running your code there to see if it might be an issue with your physical device.

Once you provide these, we should be able to help you further.

Hope you are enjoying the course!

Regards.
